
services:
  email-reply-backend:
    container_name: email-reply-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      GEMINI_API_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
      GEMINI_API_KEY: "AIzaSyDQK0dPdHR6isHJJZt2VR4ym4iqHoOuqc8"
    restart: unless-stopped
